name: mm_align
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python==3.10
  - numpy
  - cython
  - scikit-learn
  - poppler
  - pip:
    - easyocr
    - pillow
    - unstructured
    - google.generativeai
    - google
    - pdf2image
    - pytesseract
    - pandas
    - laserembeddings