name: mm_align
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pip==23.0
  - python==3.10
  - numpy
  - cython
  - sentencepiece
  - pip:
    - easyocr
    - pillow
    - unstructured
    - poppler-utils
    - google.generativeai
    - google
    - pytesseract
    - pandas
    - mcerp 
    - unicategories
    - fairseq
    - scikit-learn
    - pdf2image
    - tensorboardX